nome = str(input('Digite seu nome: '))
print('------------------------------')
sobrenome = str(input('Digite seu sobrenome: '))
print('------------------------------')
idade = int(input('Digite sua idade: '))
print('------------------------------')
anoNasc = int(input('Digite o seu ano de nascimento: '))
print('------------------------------')
maiorIdade = idade >= 18
altura = float(input('Digite sua altura em metros: '))


print(f"Nome: { nome }")
print('------------------------------')
print(f"Sobrenome: { sobrenome }")
print('------------------------------')
print(f"Idade: { idade }")
print('------------------------------')
print(f"Ano de nascimento: { anoNasc }")
print('------------------------------')
print(f"É maio de idade?: { maiorIdade }")
print('------------------------------')
print(f"Altura em metros: { altura }")
print('------------------------------')
